version: "3.8"

services:
  database:
    image: mysql:8-debian
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./containers/database/data
        target: /var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
  application:
    build:
      context: ./
      dockerfile: ./containers/application/Dockerfile
      target: application
    image: newsnow_application:latest
    ports:
      - "80:8888"
    user: "www-data"
    links:
      - database
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@database:3306/${MYSQL_DATABASE}
    depends_on:
      database:
        condition: service_healthy
